# Experimental data for charmless two-body B decays
# Using flavor states (K0, K0bar) and explicit charge labels (B+, B−, B0, Bs).

observables:
  # --- B → ππ ---
  - {mode: B0_pi+pi-,  type: BR,   value: 5.36e-6,  sigma: 0.16e-6}
  - {mode: B0_pi+pi-,  type: ACP,  value: -0.31,    sigma: 0.030}
  - {mode: B0_pi+pi-,  type: S,    value: -0.666,   sigma: 0.029}

  - {mode: B+_pi+pi0,  type: BR,   value: 5.33e-6,  sigma: 0.27e-6}
  - {mode: B+_pi+pi0,  type: ACP,  value: -0.012,   sigma: 0.031}

  - {mode: B0_pi0pi0,  type: BR,   value: 1.46e-6,  sigma: 0.14e-6}
  - {mode: B0_pi0pi0,  type: ACP,  value: 0.23,     sigma: 0.18}

  # --- B → Kπ ---
  - {mode: B0_K+pi-,   type: BR,   value: 20.07e-6, sigma: 0.40e-6}
  - {mode: B0_K+pi-,   type: ACP,  value: -0.0831,  sigma: 0.0031}

  - {mode: B0_K0pi0,   type: BR,   value: 10.1e-6,  sigma: 0.43e-6}
  - {mode: B0_K0pi0,   type: ACP,  value: -0.10,    sigma: 0.13}
  - {mode: B0_K0pi0,   type: S,    value: -0.64,     sigma: 0.13}  

  - {mode: B+_K+pi0,   type: BR,   value: 13.22e-6, sigma: 0.43e-6}
  - {mode: B+_K+pi0,   type: ACP,  value: 0.027,    sigma: 0.012}

  - {mode: B+_K0barpi+,   type: BR,   value: 23.89e-6, sigma: 0.62e-6}
  - {mode: B+_K0barpi+,   type: ACP,  value: -0.023,   sigma: 0.014}

  # --- B → KK ---
  - {mode: B+_K0K+,    type: BR,   value: 1.32e-6,  sigma: 0.14e-6}
  - {mode: B+_K0K+,    type: ACP,  value: -0.086,   sigma: 0.10}

  - {mode: B0_K+K-,    type: BR,   value: 8.21e-8,  sigma: 1.50e-8}

  - {mode: B0_K0K0bar,    type: BR,   value: 1.21e-6,  sigma: 0.16e-6}
  - {mode: B0_K0K0bar,    type: ACP,  value: -0.06,    sigma: 0.26}
  - {mode: B0_K0K0bar,    type: S,    value: -1.08,    sigma: 0.49}

  # --- Bs → KK, Kπ ---
  - {mode: Bs_K+K-,    type: BR,   value: 27.4e-6,  sigma: 3.2e-6}
  - {mode: Bs_K+K-,    type: ACP,  value: 0.17,     sigma: 0.03}
  - {mode: Bs_K+K-,    type: S,    value: 0.14,     sigma: 0.03}

  - {mode: Bs_K0K0bar,    type: BR,   value: 17.7e-6,  sigma: 3.2e-6}

  - {mode: Bs_K-pi+,   type: BR,   value: 6.08e-6,  sigma: 0.89e-6}
  - {mode: Bs_K-pi+,   type: ACP,  value: 0.225,    sigma: 0.012}
