# Priors for hadronic topologies and SU(3) breaking

hadronic:
  # Reference scale: T0 = sqrt(BR(B0->pi+pi-)) / |λ_u^(d)|
  # Each topology X is drawn as: |X| = T0 * U(min, max),  arg(X) ~ phase prior below.
  reference_phase: T   # fix arg(T)=0 to set the overall strong-phase convention

  magnitudes:
    T:  {min: 0.0, max: 2.0}
    C:  {min: 0.0, max: 2.0}
    E:  {min: 0.0, max: 2.0}
    A:  {min: 0.0, max: 2.0}
    P:  {min: 0.0, max: 2.0}
    PA: {min: 0.0, max: 2.0}

  phases:
    # Choose either uniform or Gaussian for each (except the reference which is fixed to 0)
    # uniform: {type: uniform, min: -3.141592653589793, max: 3.141592653589793}
    # gaussian: {type: gaussian, mean: 0.0, sigma: 0.7}
    T:  {type: fixed, value: 0.0}
    C:  {type: uniform,  min: -3.141592653589793, max: 3.141592653589793}
    E:  {type: uniform,  min: -3.141592653589793, max: 3.141592653589793}
    A:  {type: uniform,  min: -3.141592653589793, max: 3.141592653589793}
    P:  {type: uniform,  min: -3.141592653589793, max: 3.141592653589793}
    PA: {type: uniform,  min: -3.141592653589793, max: 3.141592653589793}

su3_breaking:
  # Multiplicative complex factors per SU(3) set, in polar form r * exp(i φ)
  magnitude:
    mean: 1.0
    sigma: 0.3
    min: 0.0   # truncate at > 0
  phase:
    min: -3.141592653589793
    max:  3.141592653589793
